### PR TITLE
Keep SOABI in extension filename

### PR DESCRIPTION
**Pull request by nforro**
Removing SOABI is not such a good idea, because it could cause problems with module loading.

Keep SOABI in extension filename and modify Makefile to handle it properly.

### CODE REVIEW

**Comment by trainman419** [comment]
Thanks!

You've been making a lot of good contributions lately; would you like direct push access to this repository?

**Comment by nforro** [comment]
Sure, you can give me access. That being said, it seems everything is working for me the way I wanted right now, so I can't guarantee there will be more contributions from me any time soon ;-)

**Comment by trainman419** [comment]
Granted: https://github.com/trainman419/python-cec/invitations ; the next time you find a bug feel free to push directly. If you think all of the bugs are worked out now, I can do a release to pypi.

**Comment by nforro** [comment]
@trainman419: Sorry for the silence. Yes, I think the recent changes are worth a new release.

**Pull request merged**
